### PR TITLE
Remove duplicate platform availability check, proper code indent

### PR DESCRIPTION
**Pull request by elsesiy**
Hey @ocReaper,

as discussed I updated your branch and did some cleaning up along the way.

I just tested it on a device, works fine.

Cheers, Jonas

### CODE REVIEW

**Comment by ocReaper** [comment]
@elsesiy Thanks for the pull request!
I will test this version on our problematic device on Monday in the office!

**Comment by elsesiy** [comment]
@ocReaper Any news on this? We need this for our planning tomorrow so if possible it'd be great to have this merged today. If not, I'll need to fork the original repo for our project myself and apply the changes directly. Thanks!

**Comment by ocReaper** [comment]
Sorry @elsesiy, but I was working on another project that had higher priority. If it acceptable for you, tomorrow morning I can test and merge your modifications. If not I can merge it now, but I may request a fix from you in case of any problem.

**Comment by elsesiy** [comment]
I'm fine with providing a fix if necessary :)

**Pull request merged**
